name = "foxford-ical-worker"
main = "build/worker/shim.mjs"
compatibility_date = "2022-12-06"

[vars]
WORKERS_RS_VERSION = "0.0.12"

[build]
command = "cargo install -q worker-build --version 0.0.7 && worker-build --release"
